version: '3.9'

services:
  apisuper:
    # container_name: wl_api_super
    build: .
    # ports:
      # - 1011:1011
    # restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - apisuper
    ports:
      - 1011:1011